### ISSUE TITLE
CRITICAL m               49 client     :Unhandled hookfn(0x7ffff0a8f3c0) {"_site":"vm.effect","type":"m.room.create"}

### ISSUE THREAD

**Issue by yangm97** [matrix-construct/construct#120]
714c0e1cc

```
2019/08/05 05:38:00.469523 2437964    ERROR resource         0 *          :socket:21868 local:45.231.133.188:8448 remote:94.237.61.93:42648 client:14710 req:139:139 Timed out in PUT `/_matrix/federation/v1/send'
2019/08/05 05:38:00.470762 2437964    ERROR m.vm            49 client     :eval $aNpWD6f76U6QQNba9Z5-rBAJGVw-QriO8OjFF8oc8Hc:yetanothernerd.xyz :interrupted :ctx:49 'client'
2019/08/05 05:38:00.471763 2437964 CRITICAL m               49 client     :Unhandled hookfn(0x7ffff0a8f3c0) {"_site":"vm.effect","type":"m.room.create"} error :500 Internal Server Error #INTERRUPT :eval $aNpWD6f76U6QQNba9Z5-rBAJGVw-QriO8OjFF8oc8Hc:yetanothernerd.xyz :interrupted :ctx:49 'client'
construct: critical log level:0: CRITICAL messages trap for debugging when assertions are enabled: Assertion `critical' failed.

Program received signal SIGABRT, Aborted.
-----------------------------------------------------------------------------------------------------------------------[regs]
  RAX: 0x0000000000000000  RBX: 0x0000000000000000  RBP: 0x00007FFFF7587858  RSP: 0x00007FFFF4B385F0  o d I t s Z a P c
  RDI: 0x0000000000000002  RSI: 0x00007FFFF4B385F0  RDX: 0x0000000000000000  RCX: 0x00007FFFF741A077  RIP: 0x00007FFFF741A077
  R8 : 0x0000000000000000  R9 : 0x00007FFFF4B385F0  R10: 0x0000000000000008  R11: 0x0000000000000246  R12: 0x00007FFFEC6A032B
  R13: 0x00007FFFEC6A033E  R14: 0x0000000000000000  R15: 0x000055555612A9D0
  CS: 0033  DS: 0000  ES: 0000  FS: 0000  GS: 0000  SS: 002B
-----------------------------------------------------------------------------------------------------------------------[code]
=> 0x7ffff741a077 <__GI_raise+199>:     mov    rcx,QWORD PTR [rsp+0x108]
   0x7ffff741a07f <__GI_raise+207>:     xor    rcx,QWORD PTR fs:0x28
   0x7ffff741a088 <__GI_raise+216>:     mov    eax,r8d
   0x7ffff741a08b <__GI_raise+219>:     jne    0x7ffff741a0ac <__GI_raise+252>
   0x7ffff741a08d <__GI_raise+221>:     add    rsp,0x118
   0x7ffff741a094 <__GI_raise+228>:     ret
   0x7ffff741a095 <__GI_raise+229>:     nop    DWORD PTR [rax]
   0x7ffff741a098 <__GI_raise+232>:     mov    rdx,QWORD PTR [rip+0x1a2dd1]        # 0x7ffff75bce70
-----------------------------------------------------------------------------------------------------------------------------
__GI_raise (sig=sig@entry=0x6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
gdb$ bt
#0  __GI_raise (sig=sig@entry=0x6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff73fb535 in __GI_abort () at abort.c:79
#2  0x00007ffff73fb40f in __assert_fail_base (fmt=0x7ffff7587858 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x7fffec6a033e "critical", file=0x7fffec6a032b "critical log level", line=0x0, function=<optimized out>) at assert.c:92
#3  0x00007ffff740b142 in __GI___assert_fail (assertion=0x7fffec6a033e "critical", file=0x7fffec6a032b "critical log level", line=0x0, function=0x7fffec69ff08 "CRITICAL messages trap for debugging when assertions are enabled") at assert.c:101
#4  0x00007fffec699975 in ircd::log::critical::critical<ircd::m::hook::hook<ircd::m::vm::eval&>*, ircd::string_view, char const*> (fmt=..., log=..., this=<optimized out>) at /usr/include/c++/8/bits/move.h:74
#5  ircd::m::hook::site<ircd::m::vm::eval&>::call (this=this@entry=0x7fffec6a6720 <ircd::m::vm::effect_hook>, hfn=..., event=..., d=...) at m/hook.h:182
#6  0x00007fffec6999d6 in ircd::m::hook::site<ircd::m::vm::eval&>::operator()(ircd::m::event const&, ircd::m::vm::eval&)::{lambda(ircd::m::hook::base&)#1}::operator()(ircd::m::hook::base&) const (base=..., this=<optimized out>) at m/hook.h:146
#7  std::_Function_handler<bool (ircd::m::hook::base&), ircd::m::hook::site<ircd::m::vm::eval&>::operator()(ircd::m::event const&, ircd::m::vm::eval&)::{lambda(ircd::m::hook::base&)#1}>::_M_invoke(std::_Any_data const&, ircd::m::hook::base&) (__functor=..., __args#0=...) at /usr/include/c++/8/bits/std_function.h:282
#8  0x00007ffff7a66e9e in std::function<void (ircd::info::versions&, ircd::buffer::mutable_buffer const&)>::operator()(ircd::info::versions&, ircd::buffer::mutable_buffer const&) const (this=this@entry=0x7ffff4b38ae0, __args#0=..., __args#1=...) at /usr/include/c++/8/bits/std_function.h:260
#9  0x00007ffff7cc2bf1 in ircd::m::hook::maps::match(ircd::m::event const&, std::function<bool (ircd::m::hook::base&)> const&) const (this=<optimized out>, event=..., callback=...) at m.cc:3794
#10 0x00007ffff7cc2c4d in ircd::m::hook::base::site::match(ircd::m::event const&, std::function<bool (ircd::m::hook::base&)> const&) (this=this@entry=0x7fffec6a6720 <ircd::m::vm::effect_hook>, event=..., callback=...) at /usr/include/c++/8/bits/unique_ptr.h:342
#11 0x00007fffec698ba8 in ircd::m::hook::site<ircd::m::vm::eval&>::operator() (this=this@entry=0x7fffec6a6720 <ircd::m::vm::effect_hook>, event=..., d=...) at m/hook.h:142
#12 0x00007fffec694c8f in ircd::m::vm::call_hook<ircd::m::vm::eval&> (hook=..., eval=..., event=..., data=...) at m_vm.cc:1083
#13 0x00007fffec69d77b in ircd::m::vm::execute (eval=..., event=...) at m_vm.cc:749
#14 0x00007fffec6972b2 in ircd::m::vm::inject3 (eval=..., event=..., contents=...) at m_vm.cc:650
#15 0x00007fffec69f79f in ircd::m::vm::inject (eval=..., event=..., contents=...) at /usr/include/c++/8/string_view:442
#16 0x00007ffff7cc449b in std::__invoke_impl<ircd::m::vm::fault, ircd::m::vm::fault (*)(ircd::m::vm::eval&, ircd::json::iov&, ircd::json::iov const&), ircd::m::vm::eval&, ircd::json::iov&, ircd::json::iov const&> (__f=<optimized out>) at /usr/include/c++/8/bits/invoke.h:89
#17 std::__invoke<ircd::m::vm::fault (*)(ircd::m::vm::eval&, ircd::json::iov&, ircd::json::iov const&), ircd::m::vm::eval&, ircd::json::iov&, ircd::json::iov const&> (__fn=<optimized out>) at /usr/include/c++/8/bits/invoke.h:95
#18 std::invoke<ircd::m::vm::fault (*)(ircd::m::vm::eval&, ircd::json::iov&, ircd::json::iov const&), ircd::m::vm::eval&, ircd::json::iov&, ircd::json::iov const&> (__fn=<optimized out>) at /usr/include/c++/8/functional:81
#19 ircd::mods::sym_ptr::operator()<ircd::m::vm::fault (ircd::m::vm::eval&, ircd::json::iov&, ircd::json::iov const&), ircd::m::vm::eval&, ircd::json::iov&, ircd::json::iov const&>(ircd::m::vm::eval&, ircd::json::iov&, ircd::json::iov const&) const (this=0x7ffff7fca8a0 <ircd::m::vm::eval::operator()(ircd::json::iov&$
 ircd::json::iov const&)::call>) at mods/sym_ptr.h:98
#20 ircd::mods::import<ircd::m::vm::fault (ircd::m::vm::eval&, ircd::json::iov&, ircd::json::iov const&)>::operator()<ircd::m::vm::eval&, ircd::json::iov&, ircd::json::iov const&>(ircd::m::vm::eval&, ircd::json::iov&, ircd::json::iov const&) (this=0x7ffff7fca8a0 <ircd::m::vm::eval::operator()(ircd::json::iov&, ircd:$
json::iov const&)::call>) at mods/import.h:158
#21 ircd::m::vm::eval::operator() (this=this@entry=0x7ffff4b3a090, event=..., contents=...) at m.cc:1539
#22 0x00007ffff7cc4553 in ircd::m::vm::eval::eval (this=0x7ffff4b3a090, event=..., content=..., opts=...) at m.cc:1368
#23 0x00007fffec9596f7 in ircd::m::_create_event (c=...) at client/createroom.cc:517
#24 0x00007fffec95f33b in ircd::m::create (c=..., errors=@0x7ffff4b3b018: 0x0) at client/createroom.cc:148
#25 0x00007ffff7c9df1f in std::__invoke_impl<ircd::m::room, ircd::m::room (*)(ircd::m::createroom const&, ircd::json::stack::array* const&), ircd::m::createroom const&, ircd::json::stack::array* const&> (__f=<optimized out>) at /usr/include/c++/8/bits/invoke.h:89
#26 std::__invoke<ircd::m::room (*)(ircd::m::createroom const&, ircd::json::stack::array* const&), ircd::m::createroom const&, ircd::json::stack::array* const&> (__fn=<optimized out>) at /usr/include/c++/8/bits/invoke.h:95
#27 std::invoke<ircd::m::room (*)(ircd::m::createroom const&, ircd::json::stack::array* const&), ircd::m::createroom const&, ircd::json::stack::array* const&> (__fn=<optimized out>) at /usr/include/c++/8/functional:81
#28 ircd::mods::sym_ptr::operator()<ircd::m::room (ircd::m::createroom const&, ircd::json::stack::array* const&), ircd::m::createroom const&, ircd::json::stack::array* const&>(ircd::m::createroom const&, ircd::json::stack::array* const&) const (this=0x7ffff7fc7b80 <ircd::m::create(ircd::m::createroom const&, ircd::j$
on::stack::array* const&)::call>) at mods/sym_ptr.h:98
#29 ircd::mods::import<ircd::m::room (ircd::m::createroom const&, ircd::json::stack::array* const&)>::operator()<ircd::m::createroom const&, ircd::json::stack::array* const&>(ircd::m::createroom const&, ircd::json::stack::array* const&) (this=0x7ffff7fc7b80 <ircd::m::create(ircd::m::createroom const&, ircd::json::st$
ck::array* const&)::call>) at mods/import.h:158
#30 ircd::m::create (c=..., errors=@0x7ffff4b3b018: 0x0) at m_room.cc:303
#31 0x00007ffff7ca13f6 in ircd::m::create (room_id=..., creator=..., preset=...) at /usr/include/c++/8/bits/stl_pair.h:208
#32 0x00007ffff7a42e05 in ircd::m::create (user_id=..., contents=...) at /usr/include/c++/8/string_view:105
#33 0x00007ffff0a672e8 in ircd::m::affect_user_room (event=..., eval=...) at m_room_member.cc:70
#34 0x00007ffff0a6a0af in std::_Function_handler<void (ircd::m::event const&, ircd::m::event::auth::hookdata&), void (*)(ircd::m::event const&, ircd::m::event::auth::hookdata&)>::_M_invoke(std::_Any_data const&, ircd::m::event const&, ircd::m::event::auth::hookdata&) (__functor=..., __args#0=..., __args#1=...) at /u$
r/include/c++/8/bits/std_function.h:88
#35 0x00007fffec69976e in std::function<void (ircd::m::event const&, ircd::m::vm::eval&)>::operator()(ircd::m::event const&, ircd::m::vm::eval&) const (this=this@entry=0x7ffff0a72f08 <ircd::m::affect_user_room_hookfn+392>, __args#0=..., __args#1=...) at /usr/include/c++/8/bits/std_function.h:260
#36 0x00007fffec699804 in ircd::m::hook::site<ircd::m::vm::eval&>::call (this=this@entry=0x7fffec6a6720 <ircd::m::vm::effect_hook>, hfn=..., event=..., d=...) at m/hook.h:155
#37 0x00007fffec6999d6 in ircd::m::hook::site<ircd::m::vm::eval&>::operator()(ircd::m::event const&, ircd::m::vm::eval&)::{lambda(ircd::m::hook::base&)#1}::operator()(ircd::m::hook::base&) const (base=..., this=<optimized out>) at m/hook.h:146
#38 std::_Function_handler<bool (ircd::m::hook::base&), ircd::m::hook::site<ircd::m::vm::eval&>::operator()(ircd::m::event const&, ircd::m::vm::eval&)::{lambda(ircd::m::hook::base&)#1}>::_M_invoke(std::_Any_data const&, ircd::m::hook::base&) (__functor=..., __args#0=...) at /usr/include/c++/8/bits/std_function.h:282
#39 0x00007ffff7a66e9e in std::function<void (ircd::info::versions&, ircd::buffer::mutable_buffer const&)>::operator()(ircd::info::versions&, ircd::buffer::mutable_buffer const&) const (this=this@entry=0x7ffff4b3b9b0, __args#0=..., __args#1=...) at /usr/include/c++/8/bits/std_function.h:260
#40 0x00007ffff7cc2bf1 in ircd::m::hook::maps::match(ircd::m::event const&, std::function<bool (ircd::m::hook::base&)> const&) const (this=<optimized out>, event=..., callback=...) at m.cc:3794
#41 0x00007ffff7cc2c4d in ircd::m::hook::base::site::match(ircd::m::event const&, std::function<bool (ircd::m::hook::base&)> const&) (this=this@entry=0x7fffec6a6720 <ircd::m::vm::effect_hook>, event=..., callback=...) at /usr/include/c++/8/bits/unique_ptr.h:342
#42 0x00007fffec698ba8 in ircd::m::hook::site<ircd::m::vm::eval&>::operator() (this=this@entry=0x7fffec6a6720 <ircd::m::vm::effect_hook>, event=..., d=...) at m/hook.h:142
#43 0x00007fffec694c8f in ircd::m::vm::call_hook<ircd::m::vm::eval&> (hook=..., eval=..., event=..., data=...) at m_vm.cc:1083
#44 0x00007fffec69d77b in ircd::m::vm::execute (eval=..., event=...) at m_vm.cc:749
#45 0x00007ffff7cc46a3 in std::__invoke_impl<ircd::m::vm::fault, ircd::m::vm::fault (*)(ircd::m::vm::eval&, ircd::m::event const&), ircd::m::vm::eval&, ircd::m::event const&> (__f=<optimized out>) at /usr/include/c++/8/bits/invoke.h:89
#46 std::__invoke<ircd::m::vm::fault (*)(ircd::m::vm::eval&, ircd::m::event const&), ircd::m::vm::eval&, ircd::m::event const&> (__fn=<optimized out>) at /usr/include/c++/8/bits/invoke.h:95
#47 std::invoke<ircd::m::vm::fault (*)(ircd::m::vm::eval&, ircd::m::event const&), ircd::m::vm::eval&, ircd::m::event const&> (__fn=<optimized out>) at /usr/include/c++/8/functional:81
#48 ircd::mods::sym_ptr::operator()<ircd::m::vm::fault (ircd::m::vm::eval&, ircd::m::event const&), ircd::m::vm::eval&, ircd::m::event const&>(ircd::m::vm::eval&, ircd::m::event const&) const (this=0x7ffff7fca7e0 <ircd::m::vm::eval::operator()(ircd::m::event const&)::call>) at mods/sym_ptr.h:98
#49 ircd::mods::import<ircd::m::vm::fault (ircd::m::vm::eval&, ircd::m::event const&)>::operator()<ircd::m::vm::eval&, ircd::m::event const&>(ircd::m::vm::eval&, ircd::m::event const&) (this=0x7ffff7fca7e0 <ircd::m::vm::eval::operator()(ircd::m::event const&)::call>) at mods/import.h:158
#50 ircd::m::vm::eval::operator() (this=this@entry=0x7ffff4b3c2f0, event=...) at m.cc:1557
#51 0x00007ffff7ccab7c in ircd::m::vm::eval::eval (this=0x7ffff4b3c2f0, pdus=..., opts=...) at m.cc:1406
#52 0x00007fffeca07f5f in handle_pdus (client=..., request=..., txn_id=..., pdus=...) at federation/send.cc:77
#53 0x00007fffeca08eb0 in handle_put (client=..., request=...) at federation/send.cc:158
#54 0x00007fffeca0dbb3 in std::_Function_handler<ircd::resource::response (ircd::client&, ircd::resource::request&), ircd::resource::response (*)(ircd::client&, ircd::resource::request::object<ircd::m::txn> const&)>::_M_invoke(std::_Any_data const&, ircd::client&, ircd::resource::request&) (__functor=..., __args#0=..
., __args#1=...) at m/txn.h:39
#55 0x00007ffff7c56601 in std::function<ircd::resource::response (ircd::client&, ircd::resource::request&)>::operator()(ircd::client&, ircd::resource::request&) const (this=this@entry=0x7fffeca12498 <method_put+24>, __args#0=..., __args#1=...) at /usr/include/c++/8/bits/std_function.h:260
#56 0x00007ffff7c527df in ircd::resource::method::call_handler (this=this@entry=0x7fffeca12480 <method_put>, client=..., request=...) at resource.cc:585
#57 0x00007ffff7c5483d in ircd::resource::method::operator() (this=0x7fffeca12480 <method_put>, client=..., head=..., content_partial=...) at resource.cc:556
#58 0x00007ffff7c47319 in ircd::client::resource_request (this=this@entry=0x5555682dafa0, head=...) at client.cc:878
#59 0x00007ffff7c47d92 in ircd::client::handle_request (this=this@entry=0x5555682dafa0, pc=...) at client.cc:799
#60 0x00007ffff7c48f94 in ircd::client::main (this=0x5555682dafa0) at client.cc:694
#61 0x00007ffff7c4b9bf in ircd::handle_client_request (client=std::shared_ptr<struct ircd::client> (use count 2, weak count 1) = {...}) at /usr/include/c++/8/bits/shared_ptr_base.h:1307
#62 0x00007ffff7c4c7f8 in std::__invoke_impl<void, void (*&)(std::shared_ptr<ircd::client>), std::shared_ptr<ircd::client>&> (__f=<optimized out>) at /usr/include/c++/8/ext/atomicity.h:96
#63 std::__invoke<void (*&)(std::shared_ptr<ircd::client>), std::shared_ptr<ircd::client>&> (__fn=<optimized out>) at /usr/include/c++/8/bits/invoke.h:95
#64 std::_Bind<void (*(std::shared_ptr<ircd::client>))(std::shared_ptr<ircd::client>)>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) (__args=..., this=<optimized out>) at /usr/include/c++/8/functional:400
#65 std::_Bind<void (*(std::shared_ptr<ircd::client>))(std::shared_ptr<ircd::client>)>::operator()<, void>() (this=<optimized out>) at /usr/include/c++/8/functional:484
#66 std::_Function_handler<void (), std::_Bind<void (*(std::shared_ptr<ircd::client>))(std::shared_ptr<ircd::client>)> >::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/include/c++/8/bits/std_function.h:297
#67 0x00005555555695fe in std::function<void ()>::operator()() const (this=<optimized out>) at /usr/include/c++/8/bits/std_function.h:260
#68 0x00007ffff7b82eb1 in ircd::ctx::pool::work (this=this@entry=0x7ffff7fc2700 <ircd::client::pool>) at ctx.cc:1510
#69 0x00007ffff7b830e8 in ircd::ctx::pool::main (this=0x7ffff7fc2700 <ircd::client::pool>) at ctx.cc:1473
#70 0x00007ffff7b85260 in std::__invoke_impl<void, void (ircd::ctx::pool::*&)() noexcept, ircd::ctx::pool*&>(std::__invoke_memfun_deref, void (ircd::ctx::pool::*&)() noexcept, ircd::ctx::pool*&) (__t=<optimized out>, __f=<optimized out>) at /usr/include/c++/8/bits/invoke.h:89
#71 std::__invoke<void (ircd::ctx::pool::*&)() noexcept, ircd::ctx::pool*&>(void (ircd::ctx::pool::*&)() noexcept, ircd::ctx::pool*&) (__fn=<optimized out>) at /usr/include/c++/8/bits/invoke.h:95
#72 std::_Bind<void (ircd::ctx::pool::*(ircd::ctx::pool*))() noexcept>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) (__args=..., this=<optimized out>) at /usr/include/c++/8/functional:400
#73 std::_Bind<void (ircd::ctx::pool::*(ircd::ctx::pool*))() noexcept>::operator()<, void>() (this=<optimized out>) at /usr/include/c++/8/functional:484
#74 std::_Function_handler<void (), std::_Bind<void (ircd::ctx::pool::*(ircd::ctx::pool*))() noexcept> >::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/include/c++/8/bits/std_function.h:297
#75 0x00005555555695fe in std::function<void ()>::operator()() const (this=<optimized out>) at /usr/include/c++/8/bits/std_function.h:260
#76 0x00007ffff7b834bb in ircd::ctx::ctx::operator()(boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >, std::function<void ()>) (this=0x5555558b4a60, yc=..., func=...) at ctx.cc:117
#77 0x00007ffff7b95b5f in std::__invoke_impl<void, void (ircd::ctx::ctx::*&)(boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >, std::function<void ()>) noexcept, ircd::ctx::ctx*&, boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::io
_context::strand> > const&, std::function<void ()>&>(std::__invoke_memfun_deref, void (ircd::ctx::ctx::*&)(boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >, std::function<void ()>) noexcept, ircd::ctx::ctx*&, boost::asio::basic_yield_context<boost::asio::executor_bind
er<void (*)(), boost::asio::io_context::strand> > const&, std::function<void ()>&) (__t=@0x5555558bd820: 0x5555558b4a60, __f=@0x5555558bd7f0: (void (ircd::ctx::ctx::*)(struct ircd::ctx::ctx * const, class boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >, class std::fu
nction<void()>)) 0x7ffff7b83450 <ircd::ctx::ctx::operator()(boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >, std::function<void ()>)>) at /usr/include/boost/asio/io_context_strand.hpp:113
#78 std::__invoke<void (ircd::ctx::ctx::*&)(boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >, std::function<void ()>) noexcept, ircd::ctx::ctx*&, boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::io_context::strand> > const&, std::
function<void ()>&>(void (ircd::ctx::ctx::*&)(boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >, std::function<void ()>) noexcept, ircd::ctx::ctx*&, boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::io_context::strand> > const&, std
::function<void ()>&) (__fn=@0x5555558bd7f0: (void (ircd::ctx::ctx::*)(struct ircd::ctx::ctx * const, class boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >, class std::function<void()>)) 0x7ffff7b83450 <ircd::ctx::ctx::operator()(boost::asio::basic_yield_context<boos
t::asio::executor_binder<void (*)(), boost::asio::executor> >, std::function<void ()>)>) at /usr/include/c++/8/bits/invoke.h:95
#79 std::_Bind<void (ircd::ctx::ctx::*(ircd::ctx::ctx*, std::_Placeholder<1>, std::function<void ()>))(boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >, std::function<void ()>) noexcept>::__call<void, boost::asio::basic_yield_context<boost::asio::executor_binder<void
(*)(), boost::asio::io_context::strand> > const&, 0ul, 1ul, 2ul>(std::tuple<boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::io_context::strand> > const&>&&, std::_Index_tuple<0ul, 1ul, 2ul>) (__args=..., this=0x5555558bd7f0) at /usr/include/c++/8/functional:400
#80 std::_Bind<void (ircd::ctx::ctx::*(ircd::ctx::ctx*, std::_Placeholder<1>, std::function<void ()>))(boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >, std::function<void ()>) noexcept>::operator()<boost::asio::basic_yield_context<boost::asio::executor_binder<void (*
)(), boost::asio::io_context::strand> > const&, void>(boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::io_context::strand> > const&) (this=0x5555558bd7f0) at /usr/include/c++/8/functional:484
#81 boost::asio::detail::coro_entry_point<boost::asio::executor_binder<void (*)(), boost::asio::io_context::strand>, std::_Bind<void (ircd::ctx::ctx::*(ircd::ctx::ctx*, std::_Placeholder<1>, std::function<void ()>))(boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >, st
d::function<void ()>) noexcept> >::operator()(boost::coroutines::pull_coroutine<void>&) (ca=..., this=<optimized out>) at /usr/include/boost/asio/impl/spawn.hpp:382
#82 boost::coroutines::detail::push_coroutine_object<boost::coroutines::pull_coroutine<void>, void, boost::asio::detail::coro_entry_point<boost::asio::executor_binder<void (*)(), boost::asio::io_context::strand>, std::_Bind<void (ircd::ctx::ctx::*(ircd::ctx::ctx*, std::_Placeholder<1>, std::function<void ()>))(boost:
:asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >, std::function<void ()>) noexcept> >&, boost::coroutines::basic_standard_stack_allocator<boost::coroutines::stack_traits> >::run() (this=this@entry=0x7ffff4b3df70) at /usr/include/boost/coroutine/detail/push_coroutine_object.
hpp:293
#83 0x00007ffff7b95dd2 in boost::coroutines::detail::trampoline_push_void<boost::coroutines::detail::push_coroutine_object<boost::coroutines::pull_coroutine<void>, void, boost::asio::detail::coro_entry_point<boost::asio::executor_binder<void (*)(), boost::asio::io_context::strand>, std::_Bind<void (ircd::ctx::ctx::*(
ircd::ctx::ctx*, std::_Placeholder<1>, std::function<void ()>))(boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >, std::function<void ()>) noexcept> >&, boost::coroutines::basic_standard_stack_allocator<boost::coroutines::stack_traits> > >(boost::context::detail::trans
fer_t) (t=...) at /usr/include/boost/coroutine/detail/trampoline_push.hpp:56
#84 0x00007ffff66b41cf in make_fcontext () from /usr/lib/x86_64-linux-gnu/libboost_context.so.1.67.0
#85 0x00007ffff7f96e68 in vtable for boost::coroutines::detail::push_coroutine_object<boost::coroutines::pull_coroutine<void>, void, boost::asio::detail::coro_entry_point<boost::asio::executor_binder<void (*)(), boost::asio::io_context::strand>, std::_Bind<void (ircd::ctx::ctx::*(ircd::ctx::ctx*, std::_Placeholder<1>
, std::function<void ()>))(boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >, std::function<void ()>) noexcept> >&, boost::coroutines::basic_standard_stack_allocator<boost::coroutines::stack_traits> > () from /opt/mutagen/construct/lib/libircd.so.3
#86 0x0000000000000006 in ?? ()
#87 0x0000000000000000 in ?? ()
gdb$ generate-core-file
warning: target file /proc/21128/cmdline contained unexpected null characters
Saved corefile core.21128
```

**Comment by jevolk** [comment]
This caused an unrecoverable SIGABRT which it's not supposed to do.
