### ISSUE TITLE
Assertion `request.started && request.finished == 0 && request.last != 0' failed.

### ISSUE THREAD

**Issue by yangm97** [matrix-construct/construct#121]
```
2019/08/07 10:53:54.254666 3841708  WARNING m.fetch         34 client     :vm:3104758:3104758:3104758 eval:69680 seq:0 share:0:0 $1fpVtdGnFhO_DKIKtXNF4iLuaGV0qqV850fHS61WAcg auth_events:4 hit:0 miss:4
construct: m_fetch.cc:1036: bool ircd::m::fetch::timedout(const ircd::m::fetch::request&, const time_t&): Assertion `request.started && request.finished == 0 && request.last != 0' failed.

Program received signal SIGABRT, Aborted.
-----------------------------------------------------------------------------------------------------------------------[regs]
  RAX: 0x0000000000000000  RBX: 0x0000000000000000  RBP: 0x00007FFFF7494588  RSP: 0x0000555555D4FCA0  o d I t s Z a P c
  RDI: 0x0000000000000002  RSI: 0x0000555555D4FCA0  RDX: 0x0000000000000000  RCX: 0x00007FFFF7320BFB  RIP: 0x00007FFFF7320BFB
  R8 : 0x0000000000000000  R9 : 0x0000555555D4FCA0  R10: 0x0000000000000008  R11: 0x0000000000000246  R12: 0x00007FFFF10FF63A
  R13: 0x00007FFFF10FE8A8  R14: 0x000000000000040C  R15: 0x0000000000067AB5
  CS: 0033  DS: 0000  ES: 0000  FS: 0000  GS: 0000  SS: 002B
-----------------------------------------------------------------------------------------------------------------------[code]
=> 0x7ffff7320bfb <__GI_raise+203>:     mov    rcx,QWORD PTR [rsp+0x108]
   0x7ffff7320c03 <__GI_raise+211>:     xor    rcx,QWORD PTR fs:0x28
   0x7ffff7320c0c <__GI_raise+220>:     mov    eax,r8d
   0x7ffff7320c0f <__GI_raise+223>:     jne    0x7ffff7320c34 <__GI_raise+260>
   0x7ffff7320c11 <__GI_raise+225>:     add    rsp,0x118
   0x7ffff7320c18 <__GI_raise+232>:     ret
   0x7ffff7320c19 <__GI_raise+233>:     nop    DWORD PTR [rax+0x0]
   0x7ffff7320c20 <__GI_raise+240>:     mov    rdx,QWORD PTR [rip+0x1a4249]        # 0x7ffff74c4e70
-----------------------------------------------------------------------------------------------------------------------------
__GI_raise (sig=sig@entry=0x6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
gdb$ bt
#0  __GI_raise (sig=sig@entry=0x6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7301855 in __GI_abort () at abort.c:79
#2  0x00007ffff7301729 in __assert_fail_base (fmt=0x7ffff7494588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x7ffff10fe8a8 "request.started && request.finished == 0 && request.last != 0", file=0x7ffff10ff63a "m_fetch.cc", line=0x40c, function=<optimized out>) at assert.c:92
#3  0x00007ffff7311986 in __GI___assert_fail (assertion=0x7ffff10fe8a8 "request.started && request.finished == 0 && request.last != 0", file=0x7ffff10ff63a "m_fetch.cc", line=0x40c, function=0x7ffff10fe858 "bool ircd::m::fetch::timedout(const ircd::m::fetch::request&, const time_t&)") at assert.c:101
#4  0x00007ffff10ef909 in ircd::m::fetch::timedout (request=..., now=@0x555555d4ff98: 0x5d4b1034) at m_fetch.cc:1036
#5  0x00007ffff10f39e2 in ircd::m::fetch::request_handle () at m_fetch.cc:660
#6  0x00007ffff10f3aec in ircd::m::fetch::request_worker () at m_fetch.cc:602
#7  0x00007ffff10f4afa in std::_Function_handler<void (), void (*)()>::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/include/c++/9/bits/std_function.h:88
#8  0x000055555556a1a2 in std::function<void ()>::operator()() const (this=<optimized out>) at /usr/include/c++/9/bits/std_function.h:263
#9  0x00007ffff7b310bb in ircd::ctx::ctx::operator()(boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >, std::function<void ()>) (this=0x555555a48770, yc=..., func=...) at ctx.cc:117
#10 0x00007ffff7b4816e in std::__invoke_impl<void, void (ircd::ctx::ctx::*&)(boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >, std::function<void ()>) noexcept, ircd::ctx::ctx*&, boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::io_context::strand> > const&, std::function<void ()>&>(std::__invoke_memfun_deref, void (ircd::ctx::ctx::*&)(boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >, std::function<void ()>) noexcept, ircd::ctx::ctx*&, boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::io_context::strand> > const&, std::function<void ()>&) (__t=@0x555555cce0c0: 0x555555a48770, __f=
    @0x555555cce090: (void (ircd::ctx::ctx::*)(struct ircd::ctx::ctx * const, class boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >, class std::function<void()>)) 0x7ffff7b31040 <ircd::ctx::ctx::operator()(boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >, std::function<void ()>)>) at /usr/include/boost/asio/io_context_strand.hpp:113
#11 std::__invoke<void (ircd::ctx::ctx::*&)(boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >, std::function<void ()>) noexcept, ircd::ctx::ctx*&, boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::io_context::strand> > const&, std::function<void ()>&>(void (ircd::ctx::ctx::*&)(boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >, std::function<void ()>) noexcept, ircd::ctx::ctx*&, boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::io_context::strand> > const&, std::function<void ()>&) (__fn=
    @0x555555cce090: (void (ircd::ctx::ctx::*)(struct ircd::ctx::ctx * const, class boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >, class std::function<void()>)) 0x7ffff7b31040 <ircd::ctx::ctx::operator()(boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >, std::function<void ()>)>) at /usr/include/c++/9/bits/invoke.h:95
#12 std::_Bind<void (ircd::ctx::ctx::*(ircd::ctx::ctx*, std::_Placeholder<1>, std::function<void ()>))(boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >, std::function<void ()>) noexcept>::__call<void, boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::io_context::strand> > const&, 0ul, 1ul, 2ul>(std::tuple<boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::io_context::strand> > const&>&&, std::_Index_tuple<0ul, 1ul, 2ul>) (__args=..., this=0x555555cce090) at /usr/include/c++/9/functional:400
#13 std::_Bind<void (ircd::ctx::ctx::*(ircd::ctx::ctx*, std::_Placeholder<1>, std::function<void ()>))(boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >, std::function<void ()>) noexcept>::operator()<boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::io_context::strand> > const&, void>(boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::io_context::strand> > const&) (this=0x555555cce090) at /usr/include/c++/9/functional:484
#14 boost::asio::detail::coro_entry_point<boost::asio::executor_binder<void (*)(), boost::asio::io_context::strand>, std::_Bind<void (ircd::ctx::ctx::*(ircd::ctx::ctx*, std::_Placeholder<1>, std::function<void ()>))(boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >, std::function<void ()>) noexcept> >::operator()(boost::coroutines::pull_coroutine<void>&) (ca=..., this=<optimized out>) at /usr/include/boost/asio/impl/spawn.hpp:382
#15 boost::coroutines::detail::push_coroutine_object<boost::coroutines::pull_coroutine<void>, void, boost::asio::detail::coro_entry_point<boost::asio::executor_binder<void (*)(), boost::asio::io_context::strand>, std::_Bind<void (ircd::ctx::ctx::*(ircd::ctx::ctx*, std::_Placeholder<1>, std::function<void ()>))(boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >, std::function<void ()>) noexcept> >&, boost::coroutines::basic_standard_stack_allocator<boost::coroutines::stack_traits> >::run() (this=this@entry=0x555555d50310)
    at /usr/include/boost/coroutine/detail/push_coroutine_object.hpp:293
#16 0x00007ffff7b48466 in boost::coroutines::detail::trampoline_push_void<boost::coroutines::detail::push_coroutine_object<boost::coroutines::pull_coroutine<void>, void, boost::asio::detail::coro_entry_point<boost::asio::executor_binder<void (*)(), boost::asio::io_context::strand>, std::_Bind<void (ircd::ctx::ctx::*(ircd::ctx::ctx*, std::_Placeholder<1>, std::function<void ()>))(boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >, std::function<void ()>) noexcept> >&, boost::coroutines::basic_standard_stack_allocator<boost::coroutines::stack_traits> > >(boost::context::detail::transfer_t) (t=...) at /usr/include/boost/coroutine/detail/trampoline_push.hpp:56
#17 0x00007ffff67f31cf in make_fcontext () from /usr/lib/x86_64-linux-gnu/libboost_context.so.1.67.0
#18 0x00007ffff7f92f08 in vtable for boost::coroutines::detail::push_coroutine_object<boost::coroutines::pull_coroutine<void>, void, boost::asio::detail::coro_entry_point<boost::asio::executor_binder<void (*)(), boost::asio::io_context::strand>, std::_Bind<void (ircd::ctx::ctx::*(ircd::ctx::ctx*, std::_Placeholder<1>, std::function<void ()>))(boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >, std::function<void ()>) noexcept> >&, boost::coroutines::basic_standard_stack_allocator<boost::coroutines::stack_traits> > () from /opt/mutagen/construct/lib/libircd.so.3
#19 0x03aa129900000006 in ?? ()
#20 0x0000000000000000 in ?? ()
gdb$ generate-core-file
warning: target file /proc/29413/cmdline contained unexpected null characters
Saved corefile core.29413
```

**Comment by jevolk** [comment]
Possibly related to #103
