### ISSUE TITLE
Assertion `!sendq.empty()' failed.

### ISSUE THREAD

**Issue by yangm97** [matrix-construct/construct#124]
```
2019/08/08 13:12:08.277719 3576459    ERROR ircd           109 m.fedsnd.R :Error from matrix.sacker.cc for 8gN8Ff2uon1zAsfVM6uDcd7Sfk6fctWtDgJJxcAiQuDT :unavailable :Peer is unable to take any requests :Connection timed out
2019/08/08 13:12:08.941769 3576663  WARNING net.dns        101 net.dns.T  :DNS timeout id:27710 on attempt 1 of 128 'im.skytel.ee'
2019/08/08 13:12:08.941966 3576663  WARNING net.dns        101 net.dns.T  :DNS timeout id:50618 on attempt 1 of 128 'chat.lnx.gr'
2019/08/08 13:12:08.942067 3576663  WARNING net.dns        101 net.dns.T  :DNS timeout id:58549 on attempt 1 of 128 'esmt.berlin'
construct: net_dns_resolver.cc:266: void ircd::net::dns::resolver::sendq_work(): Assertion `!sendq.empty()' failed.

Program received signal SIGABRT, Aborted.
-----------------------------------------------------------------------------------------------------------------------[regs]
  RAX: 0x0000000000000000  RBX: 0x0000000000000000  RBP: 0x00007FFFF7494588  RSP: 0x0000555555CB9E90  o d I t s Z a P c
  RDI: 0x0000000000000002  RSI: 0x0000555555CB9E90  RDX: 0x0000000000000000  RCX: 0x00007FFFF7320BFB  RIP: 0x00007FFFF7320BFB
  R8 : 0x0000000000000000  R9 : 0x0000555555CB9E90  R10: 0x0000000000000008  R11: 0x0000000000000246  R12: 0x00007FFFF1AEB898
  R13: 0x00007FFFF1AEB9D8  R14: 0x000000000000010A  R15: 0x000000002FD1D900
  CS: 0033  DS: 0000  ES: 0000  FS: 0000  GS: 0000  SS: 002B
-----------------------------------------------------------------------------------------------------------------------[code]
=> 0x7ffff7320bfb <__GI_raise+203>:     mov    rcx,QWORD PTR [rsp+0x108]
   0x7ffff7320c03 <__GI_raise+211>:     xor    rcx,QWORD PTR fs:0x28
   0x7ffff7320c0c <__GI_raise+220>:     mov    eax,r8d
   0x7ffff7320c0f <__GI_raise+223>:     jne    0x7ffff7320c34 <__GI_raise+260>
   0x7ffff7320c11 <__GI_raise+225>:     add    rsp,0x118
   0x7ffff7320c18 <__GI_raise+232>:     ret
   0x7ffff7320c19 <__GI_raise+233>:     nop    DWORD PTR [rax+0x0]
   0x7ffff7320c20 <__GI_raise+240>:     mov    rdx,QWORD PTR [rip+0x1a4249]        # 0x7ffff74c4e70
-----------------------------------------------------------------------------------------------------------------------------
__GI_raise (sig=sig@entry=0x6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
gdb$ bt
#0  __GI_raise (sig=sig@entry=0x6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7301855 in __GI_abort () at abort.c:79
#2  0x00007ffff7301729 in __assert_fail_base (fmt=0x7ffff7494588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x7ffff1aeb9d8 "!sendq.empty()", file=0x7ffff1aeb898 "net_dns_resolver.cc", line=0x10a, function=<optimized out>) at assert.c:92
#3  0x00007ffff7311986 in __GI___assert_fail (assertion=0x7ffff1aeb9d8 "!sendq.empty()", file=0x7ffff1aeb898 "net_dns_resolver.cc", line=0x10a, function=0x7ffff1aecbf8 "void ircd::net::dns::resolver::sendq_work()") at assert.c:101
#4  0x00007ffff1adced4 in ircd::net::dns::resolver::sendq_work (this=this@entry=0x5555559601e0) at /usr/include/c++/9/bits/std_function.h:260
#5  0x00007ffff1adcff4 in ircd::net::dns::resolver::sendq_worker (this=0x5555559601e0) at net_dns_resolver.cc:254
#6  0x00007ffff1ae0904 in std::__invoke_impl<void, void (ircd::net::dns::resolver::*&)(), ircd::net::dns::resolver*&> (__t=<optimized out>, __f=<optimized out>) at /usr/include/c++/9/bits/invoke.h:89
#7  std::__invoke<void (ircd::net::dns::resolver::*&)(), ircd::net::dns::resolver*&> (__fn=<optimized out>) at /usr/include/c++/9/bits/invoke.h:95
#8  std::_Bind<void (ircd::net::dns::resolver::*(ircd::net::dns::resolver*))()>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) (__args=..., this=<optimized out>) at /usr/include/c++/9/functional:400
#9  std::_Bind<void (ircd::net::dns::resolver::*(ircd::net::dns::resolver*))()>::operator()<, void>() (this=<optimized out>) at /usr/include/c++/9/functional:484
#10 std::_Function_handler<void (), std::_Bind<void (ircd::net::dns::resolver::*(ircd::net::dns::resolver*))()> >::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/include/c++/9/bits/std_function.h:300
#11 0x000055555556a1a2 in std::function<void ()>::operator()() const (this=<optimized out>) at /usr/include/c++/9/bits/std_function.h:263
#12 0x00007ffff7b310bb in ircd::ctx::ctx::operator()(boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >, std::function<void ()>) (this=0x5555559a6b10, yc=..., func=...) at ctx.cc:117
#13 0x00007ffff7b4816e in std::__invoke_impl<void, void (ircd::ctx::ctx::*&)(boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >, std::function<void ()>) noexcept, ircd::ctx::ctx*&, boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::io_context::strand> > const&, std::function<void ()>&>(std::__invoke_memfun_deref, void (ircd::ctx::ctx::*&)(boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >, std::function<void ()>) noexcept, ircd::ctx::ctx*&, boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::io_context::strand> > const&, std::function<void ()>&) (__t=@0x555555a97de0: 0x5555559a6b10, __f=@0x555555a97db0: (void (ircd::ctx::ctx::*)(struct ircd::ctx::ctx * const, class boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >, class std::function<void()>)) 0x7ffff7b31040 <ircd::ctx::ctx::operator()(boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >, std::function<void ()>)>) at /usr/include/boost/asio/io_context_strand.hpp:113
#14 std::__invoke<void (ircd::ctx::ctx::*&)(boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >, std::function<void ()>) noexcept, ircd::ctx::ctx*&, boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::io_context::strand> > const&, std::function<void ()>&>(void (ircd::ctx::ctx::*&)(boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >, std::function<void ()>) noexcept, ircd::ctx::ctx*&, boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::io_context::strand> > const&, std::function<void ()>&) (__fn=@0x555555a97db0: (void (ircd::ctx::ctx::*)(struct ircd::ctx::ctx * const, class boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >, class std::function<void()>)) 0x7ffff7b31040 <ircd::ctx::ctx::operator()(boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >, std::function<void ()>)>) at /usr/include/c++/9/bits/invoke.h:95
#15 std::_Bind<void (ircd::ctx::ctx::*(ircd::ctx::ctx*, std::_Placeholder<1>, std::function<void ()>))(boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >, std::function<void ()>) noexcept>::__call<void, boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::io_context::strand> > const&, 0ul, 1ul, 2ul>(std::tuple<boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::io_context::strand> > const&>&&, std::_Index_tuple<0ul, 1ul, 2ul>) (__args=..., this=0x555555a97db0) at /usr/include/c++/9/functional:400
#16 std::_Bind<void (ircd::ctx::ctx::*(ircd::ctx::ctx*, std::_Placeholder<1>, std::function<void ()>))(boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >, std::function<void ()>) noexcept>::operator()<boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::io_context::strand> > const&, void>(boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::io_context::strand> > const&) (this=0x555555a97db0) at /usr/include/c++/9/functional:484
#17 boost::asio::detail::coro_entry_point<boost::asio::executor_binder<void (*)(), boost::asio::io_context::strand>, std::_Bind<void (ircd::ctx::ctx::*(ircd::ctx::ctx*, std::_Placeholder<1>, std::function<void ()>))(boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >, std::function<void ()>) noexcept> >::operator()(boost::coroutines::pull_coroutine<void>&) (ca=..., this=<optimized out>) at /usr/include/boost/asio/impl/spawn.hpp:382
#18 boost::coroutines::detail::push_coroutine_object<boost::coroutines::pull_coroutine<void>, void, boost::asio::detail::coro_entry_point<boost::asio::executor_binder<void (*)(), boost::asio::io_context::strand>, std::_Bind<void (ircd::ctx::ctx::*(ircd::ctx::ctx*, std::_Placeholder<1>, std::function<void ()>))(boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >, std::function<void ()>) noexcept> >&, boost::coroutines::basic_standard_stack_allocator<boost::coroutines::stack_traits> >::run() (this=this@entry=0x555555cba4c0) at /usr/include/boost/coroutine/detail/push_coroutine_object.hpp:293
#19 0x00007ffff7b48466 in boost::coroutines::detail::trampoline_push_void<boost::coroutines::detail::push_coroutine_object<boost::coroutines::pull_coroutine<void>, void, boost::asio::detail::coro_entry_point<boost::asio::executor_binder<void (*)(), boost::asio::io_context::strand>, std::_Bind<void (ircd::ctx::ctx::*(ircd::ctx::ctx*, std::_Placeholder<1>, std::function<void ()>))(boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >, std::function<void ()>) noexcept> >&, boost::coroutines::basic_standard_stack_allocator<boost::coroutines::stack_traits> > >(boost::context::detail::transfer_t) (t=...) at /usr/include/boost/coroutine/detail/trampoline_push.hpp:56
#20 0x00007ffff67f31cf in make_fcontext () from /usr/lib/x86_64-linux-gnu/libboost_context.so.1.67.0
#21 0x00007ffff7f92f08 in vtable for boost::coroutines::detail::push_coroutine_object<boost::coroutines::pull_coroutine<void>, void, boost::asio::detail::coro_entry_point<boost::asio::executor_binder<void (*)(), boost::asio::io_context::strand>, std::_Bind<void (ircd::ctx::ctx::*(ircd::ctx::ctx*, std::_Placeholder<1>, std::function<void ()>))(boost::asio::basic_yield_context<boost::asio::executor_binder<void (*)(), boost::asio::executor> >, std::function<void ()>) noexcept> >&, boost::coroutines::basic_standard_stack_allocator<boost::coroutines::stack_traits> > () from /opt/mutagen/construct/lib/libircd.so.3
#22 0x0000000000000006 in ?? ()
#23 0x0000000000000000 in ?? ()
gdb$ generate-core-file
warning: target file /proc/7084/cmdline contained unexpected null characters
Saved corefile core.7084
```

**Comment by jevolk** [comment]
Thanks, this looks juicy.
